/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e8e8e8",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f0f1f1",
        background: "#f9f9f9",
        "on-tertiary": "#ffffff",
        primary: "#9e0000",
        outline: "#926e69",
        "outline-variant": "#e8bdb6",
        "surface-bright": "#f9f9f9",
        tertiary: "#4b4d4d",
        "on-primary": "#ffffff",
        "surface-variant": "#e2e2e2",
        "primary-fixed-dim": "#ffb4a8",
        "surface-container-highest": "#e2e2e2",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#1c1b1b",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        "surface-dim": "#dadada",
        "on-primary-fixed-variant": "#930000",
        "on-error": "#ffffff",
        "secondary-container": "#e2dfde",
        "primary-container": "#cc0000",
        "inverse-primary": "#ffb4a8",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#c00000",
        "secondary-fixed": "#e5e2e1",
        surface: "#f9f9f9",
        "secondary-fixed-dim": "#c8c6c5",
        "on-surface-variant": "#5e3f3a",
        "on-surface": "#1a1c1c",
        "surface-container": "#eeeeee",
        secondary: "#5f5e5e",
        "on-primary-container": "#ffdad4",
        "on-tertiary-fixed-variant": "#454747",
        "on-primary-fixed": "#410000",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-container": "#e2e3e3",
        "on-background": "#1a1c1c",
        "tertiary-container": "#636565",
        "primary-fixed": "#ffdad4",
        "inverse-surface": "#2f3131",
        "on-secondary-container": "#636262",
        "tertiary-fixed": "#e2e2e2",
        "surface-container-low": "#f3f3f4",
        "on-tertiary-fixed": "#1a1c1c",
        "on-secondary-fixed-variant": "#474746",
        "pava-accent": "#F3A905",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "80px",
        sm: "12px",
        "container-max": "1200px",
        md: "24px",
        lg: "48px",
        xs: "4px",
        gutter: "24px",
        base: "8px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "label-bold": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-xl": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-bold": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
